In [2]:
import numpy as np

a = np.random.randn(5)

print(a)

[ 0.22724512 -0.5091454   0.582201   -0.9838475   0.0012797 ]


In [3]:
print(a.shape)

(5,)


In [4]:
# This is a 'rank 1 array' in python, this leads to some non-intuitive effects:
print(a.T) # a transpose

[ 0.22724512 -0.5091454   0.582201   -0.9838475   0.0012797 ]


In [5]:
print(np.dot(a,a.T))

1.61778492989


In [6]:
# Instead, use this:
a = np.random.randn(5,1)
print(a)

[[ 0.6717134 ]
 [-0.80392574]
 [-0.82180558]
 [-0.48927179]
 [-0.1398177 ]]


In [7]:
print(a.T)

[[ 0.6717134  -0.80392574 -0.82180558 -0.48927179 -0.1398177 ]]


In [8]:
print(np.dot(a,a.T))

[[ 0.4511989  -0.5400077  -0.55201782 -0.32865042 -0.09391742]
 [-0.5400077   0.6462966   0.66067066  0.39333819  0.11240305]
 [-0.55201782  0.66067066  0.67536442  0.40208629  0.11490297]
 [-0.32865042  0.39333819  0.40208629  0.23938689  0.06840886]
 [-0.09391742  0.11240305  0.11490297  0.06840886  0.01954899]]


In [11]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)
